name: Deploy External API-zevallos-y-anahua

on:
  push:
    branches:
      - ApisFunciones

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repository
        uses: actions/checkout@v3
        with:
          path: api-repo  # Directorio donde se descargará tu repositorio

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        working-directory: ./api-repo/api_lugares  # Actualiza el directorio de trabajo
        run: |
          python -m venv env
          source env/bin/activate
          pip install -r requirements.txt

      - name: Build Docker image
        working-directory: ./api-repo/api_lugares  # Navega al directorio donde está el Dockerfile
        run: docker build -t api-eventos -f Dockerfile .

      - name: Run Docker container
        run: docker run -d -p 8000:8000 api-eventos
