name: Deploy External API-zevallos-y-anahua

on:
  push:
    branches:
      - ApisFunciones

jobs:
  build:
    runs-on: ubuntu-latest  # Cambiado a Ubuntu para compatibilidad con Docker

    steps:
      - name: Checkout your repository
        uses: actions/checkout@v3

      - name: Clone external repository (Desarrollo branch)
        run: git clone --single-branch --branch Desarrollo https://github.com/UPT-FAING-EPIS/proyecto-si8811a-2024-ii-u1-api-y-funciones-zevallos-y-anahua.git external-repo

      - name: Build Docker image
        working-directory: ./external-repo/api_lugares
        run: docker build -t api-eventos .

      - name: Run Docker container
        run: docker run -d -p 8001:8000 api-eventos
        # Map port 8000 inside the container to port 8001 on the host for clarity
