name: Deploy External API-zevallos-y-anahua

on:
  push:
    branches:
      - ApisFunciones

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repository
        uses: actions/checkout@v3

      - name: Clone external repository (Development branch)
        run: git clone --single-branch --branch Desarrollo https://github.com/UPT-FAING-EPIS/proyecto-si8811a-2024-ii-u1-api-y-funciones-zevallos-y-anahua.git external-repo

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Prepare custom requirements
        run: |
          echo "absl-py==2.1.0" > external-repo/api_eventos/custom-requirements.txt
          echo "astunparse==1.6.3" >> external-repo/api_eventos/custom-requirements.txt
          echo "blinker==1.8.2" >> external-repo/api_eventos/custom-requirements.txt
          echo "certifi==2024.7.4" >> external-repo/api_eventos/custom-requirements.txt
          echo "charset-normalizer==3.3.2" >> external-repo/api_eventos/custom-requirements.txt
          echo "click==8.1.7" >> external-repo/api_eventos/custom-requirements.txt
          echo "colorama==0.4.6" >> external-repo/api_eventos/custom-requirements.txt
          echo "Flask==3.0.3" >> external-repo/api_eventos/custom-requirements.txt
          echo "Flask-Testing==0.8.1" >> external-repo/api_eventos/custom-requirements.txt
          echo "flatbuffers==24.3.25" >> external-repo/api_eventos/custom-requirements.txt
          echo "gast==0.6.0" >> external-repo/api_eventos/custom-requirements.txt
          echo "google-pasta==0.2.0" >> external-repo/api_eventos/custom-requirements.txt
          echo "greenlet==3.0.3" >> external-repo/api_eventos/custom-requirements.txt
          echo "grpcio==1.66.0" >> external-repo/api_eventos/custom-requirements.txt
          echo "h5py==3.11.0" >> external-repo/api_eventos/custom-requirements.txt
          echo "idna==3.8" >> external-repo/api_eventos/custom-requirements.txt
          echo "itsdangerous==2.2.0" >> external-repo/api_eventos/custom-requirements.txt
          echo "Jinja2==3.1.4" >> external-repo/api_eventos/custom-requirements.txt
          echo "joblib==1.4.2" >> external-repo/api_eventos/custom-requirements.txt
          echo "keras==2.15.0" >> external-repo/api_eventos/custom-requirements.txt  # Usa una versión compatible
          echo "libclang==18.1.1" >> external-repo/api_eventos/custom-requirements.txt
          echo "Markdown==3.7" >> external-repo/api_eventos/custom-requirements.txt
          echo "markdown-it-py==3.0.0" >> external-repo/api_eventos/custom-requirements.txt
          echo "MarkupSafe==2.1.5" >> external-repo/api_eventos/custom-requirements.txt
          echo "mdurl==0.1.2" >> external-repo/api_eventos/custom-requirements.txt
          echo "ml-dtypes==0.4.0" >> external-repo/api_eventos/custom-requirements.txt
          echo "namex==0.0.8" >> external-repo/api_eventos/custom-requirements.txt
          echo "numpy==1.26.4" >> external-repo/api_eventos/custom-requirements.txt
          echo "opt-einsum==3.3.0" >> external-repo/api_eventos/custom-requirements.txt
          echo "optree==0.12.1" >> external-repo/api_eventos/custom-requirements.txt
          echo "packaging==24.1" >> external-repo/api_eventos/custom-requirements.txt
          echo "protobuf==4.25.4" >> external-repo/api_eventos/custom-requirements.txt
          echo "Pygments==2.18.0" >> external-repo/api_eventos/custom-requirements.txt
          echo "requests==2.32.3" >> external-repo/api_eventos/custom-requirements.txt
          echo "rich==13.7.1" >> external-repo/api_eventos/custom-requirements.txt
          echo "scikit-learn==1.5.1" >> external-repo/api_eventos/custom-requirements.txt
          echo "scipy==1.10.1" >> external-repo/api_eventos/custom-requirements.txt  # Usa una versión compatible
          echo "setuptools==73.0.1" >> external-repo/api_eventos/custom-requirements.txt
          echo "six==1.16.0" >> external-repo/api_eventos/custom-requirements.txt
          echo "SQLAlchemy==2.0.32" >> external-repo/api_eventos/custom-requirements.txt
          echo "tensorboard==2.17.1" >> external-repo/api_eventos/custom-requirements.txt
          echo "tensorboard-data-server==0.7.2" >> external-repo/api_eventos/custom-requirements.txt
          echo "tensorflow==2.17.0" >> external-repo/api_eventos/custom-requirements.txt
          echo "termcolor==2.4.0" >> external-repo/api_eventos/custom-requirements.txt
          echo "threadpoolctl==3.5.0" >> external-repo/api_eventos/custom-requirements.txt
          echo "typing_extensions==4.12.2" >> external-repo/api_eventos/custom-requirements.txt
          echo "urllib3==2.2.2" >> external-repo/api_eventos/custom-requirements.txt
          echo "Werkzeug==3.0.4" >> external-repo/api_eventos/custom-requirements.txt
          echo "wheel==0.44.0" >> external-repo/api_eventos/custom-requirements.txt
          echo "wrapt==1.16.0" >> external-repo/api_eventos/custom-requirements.txt

      - name: Verify custom requirements file
        run: |
          ls -la external-repo/api_eventos/
          cat external-repo/api_eventos/custom-requirements.txt

      - name: Install dependencies
        working-directory: ./external-repo/api_eventos
        run: |
          python -m venv env
          . env/bin/activate
          pip install --upgrade pip
          pip install -r custom-requirements.txt

      - name: Build Docker image for API
        working-directory: ./external-repo/api_eventos
        run: |
          docker build -t palbertt/api-zevallos-y-anahua:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker image for API
        run: |
          docker push palbertt/api-zevallos-y-anahua:latest
