name: Deploy External API-zevallos-y-anahua

on:
  push:
    branches:
      - ApisFunciones
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout your repository
        uses: actions/checkout@v3

      - name: Clone external repository (Desarrollo branch)
        run: git clone --single-branch --branch Desarrollo https://github.com/UPT-FAING-EPIS/proyecto-si8811a-2024-ii-u1-api-y-funciones-zevallos-y-anahua.git external-repo

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        working-directory: ./external-repo/api_eventos
        run: |
          python -m venv env
          .\env\Scripts\activate
          pip install -r requirements.txt

      - name: Build Docker image
        working-directory: ./external-repo/api_eventos
        run: docker build -t api-eventos .

      - name: Run Docker container
        run: docker run -d -p 8001:8001 api-eventos
