name: CI/CD Pipeline

on:
  push:
    branches:
      - ApisFunciones  # Cambia esto según la rama correcta que uses

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout current repository
      uses: actions/checkout@v3
      with:
        repository: UPT-FAING-EPIS/proyecto-si8811a-2024-ii-u1-apis-y-funciones-meza-y-churacutipa
        ref: desarrollo

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12  # La versión que usa el Dockerfile

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

    # Agregar paso para iniciar sesión en Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .  # Directorio del repositorio actual
        file: Dockerfile  # Usa el Dockerfile del proyecto
        push: true
        tags: palbertt/proyecto-si8811a-2024-ii-u1-apis-y-funciones-meza-y-churacutipa:api1-v1.0.0

    - name: Deploy Docker Container
      run: |
        docker run -d -p 5000:5000 palbertt/proyecto-si8811a-2024-ii-u1-apis-y-funciones-meza-y-churacutipa:api1-v1.0.0

    
