name: Deploy External API-zevallos-y-anahua

on:
  push:
    branches:
      - ApisFunciones

jobs:
  build:
    runs-on: ubuntu-latest  # Cambiado a Ubuntu para compatibilidad con Docker

    steps:
      - name: Checkout your repository
        uses: actions/checkout@v3

      - name: Clone external repository (Desarrollo branch)
        run: git clone --single-branch --branch Desarrollo https://github.com/UPT-FAING-EPIS/proyecto-si8811a-2024-ii-u1-api-y-funciones-zevallos-y-anahua.git external-repo

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        working-directory: ./external-repo/api_lugares
        run: |
          python -m venv env
          source env/bin/activate
          pip install -r requirements.txt

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./external-repo/api_lugares  # Directorio del contexto de construcción
          file: Dockerfile  # Usa el Dockerfile del proyecto
          push: true
          tags: palbertt/proyecto-si8811a-2024-ii-u1-api-y-funciones-zevallos-y-anahua:api2-v1.0.0

      - name: Deploy Docker Container
        run: |
          docker run -d -p 5000:5000 palbertt/proyecto-si8811a-2024-ii-u1-api-y-funciones-zevallos-y-anahua:api2-v1.0.0
