name: CI/CD Pipeline

on:
  push:
    branches:
      - ApisFunciones

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout current repository
      uses: actions/checkout@v3
      with:
        repository: UPT-FAING-EPIS/proyecto-si8811a-2024-ii-u1-apis-y-funciones-meza-y-churacutipa
        ref: ApisFunciones  # La rama del repositorio principal si es necesario

    - name: Checkout external repository
      uses: actions/checkout@v3
      with:
        repository: UPT-FAING-EPIS/proyecto-si8811a-2024-ii-u1-apis-y-funciones-meza-y-churacutipa
        token: ${{ secrets.GITHUB_TOKEN }}
        path: external-repo  # Directorio donde se clonará el repositorio externo

    - name: List files in the repository
      run: |
        echo "Listing files in the current directory:"
        ls -la
        echo "Listing files in the external-repo directory:"
        ls -la external-repo

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        cd external-repo  # Navega al directorio del repositorio externo
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; else echo "requirements.txt not found"; exit 1; fi

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: external-repo  # Directorio del repositorio externo
        file: Dockerfile
        push: true
        tags: your-docker-repo/my-flask-app:latest

    - name: Deploy Docker Container
      run: |
        docker run -d -p 5000:5000 your-docker-repo/my-flask-app:latest


