name: Generate Infrastructure Diagrams

on:
  push:
    branches:
      - DesarrolloApiBack
      - main

jobs:
  generate-diagrams:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/DesarrolloApiBack'  # Only run this job on DesarrolloApiBack

    steps:
      - name: Checkout the main repository
        uses: actions/checkout@v3

      - name: Checkout the Terraform repository
        uses: actions/checkout@v3
        with:
          repository: UPT-FAING-EPIS/proyecto-si8811a-2024-ii-u1-desarrollo-api-back
          path: terraform_repo
          ref: develop

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y graphviz
          # Install Node.js and npm
          sudo apt install -y nodejs npm
          # Install terraform-visual globally
          sudo npm install -g terraform-visual

      - name: Generate PNG Diagrams
        run: |
          for tf_file in $(find terraform_repo -name "main.tf"); do
              echo "Generating diagram for $tf_file"
              terraform-visual -f "$tf_file" -o "${tf_file%.tf}.png"
          done

      - name: Commit and Push Diagrams
        run: |
          git config --local user.name "jesus huallpa"
          git config --local user.email "jh2021071085@virtual.upt.pe"
          git add *.png  # Ensure the generated images are in the root or adjust the pattern
          git commit -m "Automatically generate infrastructure diagrams" || echo "No changes to commit"
          git push origin DesarrolloApiBack

  install:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Only run this job on main

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y graphviz
          # Install Node.js and npm
          sudo apt install -y nodejs npm
          # Install terraform-visual globally
          sudo npm install -g terraform-visual

