name: CI/CD Pipeline for .NET API

on:
  push:
    branches:
      - ApiFuncion

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Hacer checkout del repositorio actual
    - name: Checkout current repository
      uses: actions/checkout@v3

    # Hacer checkout del Dockerfile y el archivo .csproj desde el otro repositorio
    - name: Checkout Dockerfile and project file from another repository
      uses: actions/checkout@v3
      with:
        repository: UPT-FAING-EPIS/proyecto-si8811a-2024-ii-u1-desarrollo-api-back
        ref: desarrollo
        token: ${{ secrets.GITHUB_TOKEN }}
        path: dockerfile-repo  # Descarga el otro repositorio en este subdirectorio

    # Listar archivos para debugging
    - name: List files for debugging
      run: ls -R dockerfile-repo  # Lista los archivos para verificar la estructura del directorio

    # Configurar .NET Core SDK
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'  # Versión que estás utilizando

    # Restaurar las dependencias de .NET
    - name: Restore .NET dependencies
      run: dotnet restore dockerfile-repo/proyecto-si8811a-2024-ii-u1-desarrollo-api-back.csproj

    # Construir la aplicación .NET
    - name: Build .NET application
      run: dotnet build dockerfile-repo/proyecto-si8811a-2024-ii-u1-desarrollo-api-back.csproj --configuration Release --no-restore

    # Ejecutar las pruebas de .NET
    - name: Test .NET application
      run: dotnet test dockerfile-repo/proyecto-si8811a-2024-ii-u1-desarrollo-api-back.csproj --configuration Release --no-build --verbosity normal

    # Configurar Docker Buildx para la construcción de imágenes Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Iniciar sesión en Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    # Construir y enviar la imagen Docker al registro
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: dockerfile-repo  # Usa el directorio donde se descargó el Dockerfile
        file: dockerfile-repo/Dockerfile  # Ruta al Dockerfile descargado
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/proyecto-si8811a-2024-ii-u1-desarrollo-api-back:latest
