name: Build and Push Docker Images

on:
  push:
    branches:
      - automatizacion

jobs:
  build-images:
    runs-on: ubuntu-latest

    steps:
      # Checkout el repositorio con el Dockerfile
      - name: Checkout the pruebas repository
        uses: actions/checkout@v3
        with:
          repository: UPT-FAING-EPIS/proyecto-si8811a-2024-ii-u1-pruebas-cano-valverde
          ref: main

      # Login en Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Crear un Dockerfile temporal
      - name: Create Dockerfile
        run: |
          echo 'FROM python:3.9-slim' > Dockerfile
          echo 'WORKDIR /app' >> Dockerfile
          echo 'COPY requirements.txt .' >> Dockerfile  # Este archivo debería estar en la raíz del checkout
          echo 'RUN pip install --no-cache-dir -r requirements.txt' >> Dockerfile
          echo 'COPY . .' >> Dockerfile
          echo 'CMD ["python", "app.py"]' >> Dockerfile

      # Build y push de la imagen
      - name: Build Docker image for application
        run: |
          docker build -t palbertt/proyecto-si8811a-2024-ii-u1-pruebas-cano-valverde:Selenium

      - name: Push Docker image for application
        run: |
          docker push palbertt/proyecto-si8811a-2024-ii-u1-pruebas-cano-valverde:Selenium
