name: Build and Push Docker image

on:
  push:
    branches:
      - automatizacion

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository with the Dockerfile
        uses: actions/checkout@v3
        with:
          repository: UPT-FAING-EPIS/proyecto-si8811a-2024-ii-u1-desarrollo-api-back
          ref: desarrollo

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t palbertt/automatizacion:latest .

      - name: Push Docker image
        run: |
          docker push palbertt/automatizacion:latest
