name: Build and Push Docker images

on:
  push:
    branches:
      - automatizacion

jobs:
  build-application:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository with the Dockerfile
        uses: actions/checkout@v3
        with:
          repository: UPT-FAING-EPIS/proyecto-si8811a-2024-ii-u1-desarrollo-api-back
          ref: desarrollo

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image for application
        run: |
          docker build -t palbertt/automatizacion:latest .

      - name: Push Docker image for application
        run: |
          docker push palbertt/automatizacion:latest

  build-infrastructure:
    runs-on: ubuntu-latest
    needs: build-application
    steps:
      - name: Checkout the repository with the infrastructure Dockerfile
        uses: actions/checkout@v3
        with:
          repository: UPT-FAING-EPIS/proyecto-si8811a-2024-ii-u1-desarrollo-api-back
          ref: develop

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image for infrastructure
        run: |
          docker build -t palbertt/infrastructure-automation:latest -f path/to/infrastructure/Dockerfile .

      - name: Push Docker image for infrastructure
        run: |
          docker push palbertt/infrastructure-automation:latest
