name: Build and Push Docker image infrastructure

on:
  push:
    branches:
      - infrastructure-automation

jobs:
  build:
    runs-on: ubuntu-latest  # Run the workflow on a Linux environment

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          repository: UPT-FAING-EPIS/proyecto-si8811a-2024-ii-u1-desarrollo-api-back
          ref: develop  # Branch where the Dockerfile is located

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t palbertt/automatizacion:latest .

      - name: Push Docker image
        run: |
          docker push palbertt/automatizacion:latest
