name: Generate Diagram

on:
  push:
    branches:
      - DesarrolloApiBack

jobs:
  generate-diagram:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the main repository
        uses: actions/checkout@v3

      - name: Checkout the Terraform repository
        uses: actions/checkout@v3
        with:
          repository: UPT-FAING-EPIS/proyecto-si8811a-2024-ii-u1-desarrollo-api-back
          path: terraform_repo
          ref: develop

      - name: Install Terraform
        run: |
          curl -LO https://releases.hashicorp.com/terraform/1.0.0/terraform_1.0.0_linux_amd64.zip
          unzip terraform_1.0.0_linux_amd64.zip
          sudo mv terraform /usr/local/bin/

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz python3-pip

      - name: Install Python Modules
        run: |
          pip3 install graphviz numpy==1.21.0 GitPython tqdm debugpy ipaddr

      - name: Clone Terravision Repository
        run: |
          git clone https://github.com/patrickchugh/terravision.git
          cd terravision
          chmod +x terravision
          export PATH=$PATH:$(pwd)

      - name: Generate Diagram
        run: |
          cd terravision
          ./terravision draw --source ../terraform_repo
          mv output.png ../diagram.png || echo "El archivo no se generó como se esperaba"

      - name: Commit and Push Diagram
        run: |
          git config --local user.name "jesus huallpa"
          git config --local user.email "jh2021071085@virtual.upt.pe"
          if [ -f "diagram.png" ]; then
            git add diagram.png
            git commit -m "Generar diagrama automáticamente" || echo "No hay cambios para commit"
            git push origin DesarrolloApiBack
          else
            echo "El archivo diagram.png no se generó"
          fi
