name: Generate Infrastructure Diagram

on:
  push:
    branches:
      - automatizacion

jobs:
  generate-diagram:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          repository: UPT-FAING-EPIS/proyecto-si8811a-2024-ii-u1-desarrollo-api-back
          ref: develop

      - name: Generate Mermaid Diagram
        id: generate_mermaid
        run: |
          # Extraer información de main.tf
          main_tf_content=$(cat main.tf)

          # Generar diagrama Mermaid
          echo "graph TD;" > diagram.mermaid

          # Buscar módulos en el main.tf
          while IFS= read -r line; do
            if [[ $line == module* ]]; then
              module_name=$(echo $line | awk '{print $2}')
              echo "    $module_name[$module_name] --> AWS" >> diagram.mermaid
            fi
          done <<< "$main_tf_content"

          # Verificar el contenido del diagrama
          echo "Contenido del diagrama generado:"
          cat diagram.mermaid

      - name: Update README.md
        run: |
          echo "# Proyecto de API" > README.md
          echo "" >> README.md
          echo "Este proyecto contiene funciones automatizadas para gestionar la API." >> README.md
          echo "" >> README.md
          echo "## Diagrama de Infraestructura" >> README.md
          echo '```mermaid' >> README.md
          echo "graph TD;" >> README.md
          echo "    grafana[GRAFANA] --> AWS" >> README.md
          echo "    mongodb[MONGODB] --> AWS" >> README.md
          echo "    web_app[APLICACIÓN WEB] --> AWS" >> README.md
          echo "    mobile_app[APLICACIÓN MÓVIL] --> AWS" >> README.md
          echo "    backend_api[API BACKEND] --> AWS" >> README.md
          echo '```' >> README.md
          echo "" >> README.md
          echo "## Recursos Utilizados" >> README.md
          echo "- EC2" >> README.md
          echo "- MongoDB" >> README.md
          echo "- Grafana" >> README.md
          echo "- Aplicaciones Web y Móviles" >> README.md
          echo "- API Backend" >> README.md

      - name: Commit and Push README.md
        run: |
          git config --local user.name "jesus huallpa"
          git config --local user.email "jh2021071085@virtual.upt.pe"
          git add README.md
          git commit -m "Actualizar README.md con diagrama de infraestructura" || echo "No hay cambios para commitear"
          git push origin automatizacion
