name: Selenium Tests and Deploy to GitHub Pages

# Ejecutar el workflow en tu repositorio cuando haya un push o pull request a la rama main
on:
  push:
    branches:
      - main  # Aquí va tu rama actual
  pull_request:
    branches:
      - main  # Aquí va tu rama actual

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout de tu propio repositorio y rama actual
      - name: Checkout your repository
        uses: actions/checkout@v3

      # Paso 2: Clonar el repositorio externo en la rama 'feature/feature_pruebas'
      - name: Checkout external repository
        uses: actions/checkout@v3
        with:
          repository: UPT-FAING-EPIS/proyecto-si8811a-2024-ii-u1-pruebas-cano-valverde
          ref: feature/feature_pruebas

      # Paso 3: Configurar Java para las pruebas de Selenium
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # Paso 4: Instalar Chrome para Selenium
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      # Paso 5: Instalar ChromeDriver
      - name: Set up Chrome WebDriver
        run: |
          sudo apt-get install -y unzip xvfb
          wget -q -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
          unzip /tmp/chromedriver.zip -d /usr/local/bin/

      # Paso 6: Instalar las dependencias del proyecto (ajusta según tu stack, puede ser Maven o Node.js)
      - name: Install dependencies
        run: |
          ./mvnw install

      # Paso 7: Ejecutar las pruebas de Selenium usando Chrome en modo headless
      - name: Run Selenium tests
        run: |
          xvfb-run --auto-servernum --server-args='-screen 0 1920x1080x24' ./mvnw test

      # Paso 8: Guardar los reportes de las pruebas
      - name: Archive test reports
        if: always()
        run: mkdir -p target/test-reports

      # Paso 9: Desplegar los reportes de las pruebas en GitHub Pages
      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/surefire-reports
