name: Download and Setup Selenium Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-selenium-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Check README.md
      run: |
        if [ -f README.md ]; then
          echo "README.md found."
        else
          echo "README.md not found!"
          exit 1
        fi
