name: Download and Setup Selenium Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-selenium-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout your repo
      uses: actions/checkout@v3

    - name: Clone Selenium Test Repo
      run: |
        git clone https://github.com/UPT-FAING-EPIS/proyecto-si8811a-2024-ii-u1-pruebas-cano-valverde
        cp -r proyecto-si8811a-2024-ii-u1-pruebas-cano-valverde/* .

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest --alluredir=./allure-results --browser=chrome
        pytest --alluredir=./allure-results --browser=firefox

    - name: Generate Allure report
      run: |
        allure generate ./allure-results -o ./allure-report --clean

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure-report
